services:
  - type: web
    name: buildbuddy-api
    runtime: python
    buildCommand: pip install -r requirements-production.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: buildbuddy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: buildbuddy-db
    databaseName: buildbuddy
    user: buildbuddy
